---
- name: Create homepage namespace
  kubernetes.core.k8s:
    kubeconfig: /var/snap/microk8s/current/credentials/client.config
    name: homepage
    api_version: v1
    kind: Namespace
    state: present

- name: Copy k8s config files to Node
  become: true
  copy:
    src: /home/vagrant/ansible/playbooks/roles/microk8s_homepage/files/
    dest: /tmp/

- name: Fetch IP address of Host
  vars:
    command: "hostname -I | awk '{print $1}'"
  shell: "{{ command }}"
  register: host_ip

- name: Host IP
  debug:
    var: host_ip.stdout

- name: Create configMap from template
  become: true
  template:
    src: configmap_homepage.j2
    dest: /tmp/configmap_homepage.yml

- name: Apply  configMap
  kubernetes.core.k8s:
    kubeconfig: /var/snap/microk8s/current/credentials/client.config
    state: present
    namespace: homepage
    src: /tmp/configmap_homepage.yml

- name: Create deployment
  kubernetes.core.k8s:
    kubeconfig: /var/snap/microk8s/current/credentials/client.config
    state: present
    namespace: homepage
    src: /tmp/deployment_homepage.yml

- name: Create service from template
  become: true
  template:
    src: service_homepage.j2
    dest: /tmp/service_homepage.yml

- name: Create service
  kubernetes.core.k8s:
    kubeconfig: /var/snap/microk8s/current/credentials/client.config
    state: present
    namespace: homepage
    src: /tmp/service_homepage.yml