apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress_restore
  namespace: wordpress-restore
  labels:
    app: wordpress_restore
spec:
  selector:
    matchLabels:
      app: wordpress_restore
  template:
    metadata:
      labels:
        app: wordpress_restore
    spec:
      containers:
      - image: wordpress:6.3.2-apache
        imagePullPolicy: Always
        name: wordpress-restore
        env:
        - name: WORDPRESS_DB_HOST
          value: mysql-restore
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret-restore
              key: PASSWORD
        - name: WORDPRESS_DB_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secret-restore
              key: USER
        ports:
        - containerPort: 80
          name: wordpress-restore
        volumeMounts:
        - name: wordpress-persistent-storage-restore
          mountPath: /var/www/html
      volumes:
      - name: wordpress-persistent-storage-restore
        persistentVolumeClaim:
          claimName: wordpress-pv-claim-restore