---
- name: Create mount points on MicroK8s Node | postgres
  ansible.builtin.file:
    path: /mnt/storage/wikijs/postgres
    state: directory
    mode: '0755'
    owner: nobody
    group: nogroup

- name: Create mount points on MicroK8s Node | wikijs
  ansible.builtin.file:
    path: /mnt/storage/wikijs/wikijs
    state: directory
    mode: '0777'
    owner: nobody
    group: nogroup

- name: Create wikijs namespace
  kubernetes.core.k8s:
    kubeconfig: /var/snap/microk8s/current/credentials/client.config
    name: wikijs
    api_version: v1
    kind: Namespace
    state: present

- name: Copy k8s yaml files to Node
  become: true
  copy:
    src: /home/vagrant/ansible/playbooks/roles/microk8s_wikijs/files/
    dest: /tmp/

- name: Apply Secrets
  kubernetes.core.k8s:
    kubeconfig: /var/snap/microk8s/current/credentials/client.config
    state: present
    namespace: wikijs
    src: /tmp/secrets_postgres.yml

- name: Create Persistent Volume | wikijs
  kubernetes.core.k8s:
    kubeconfig: /var/snap/microk8s/current/credentials/client.config
    state: present
    namespace: wikijs
    src: /tmp/pv_wikijs.yml

- name: Create Persistent Volume Claim | wikijs
  kubernetes.core.k8s:
    kubeconfig: /var/snap/microk8s/current/credentials/client.config
    state: present
    namespace: wikijs
    src: /tmp/pvc_wikijs.yml

- name: Create Persistent Volume | wikijs_db
  kubernetes.core.k8s:
    kubeconfig: /var/snap/microk8s/current/credentials/client.config
    state: present
    namespace: wikijs
    src: /tmp/pv_postgres.yml

- name: Create Persistent Volume Claim | wikijs_db
  kubernetes.core.k8s:
    kubeconfig: /var/snap/microk8s/current/credentials/client.config
    state: present
    namespace: wikijs
    src: /tmp/pvc_postgres.yml

- name: Create Config Map
  kubernetes.core.k8s:
    kubeconfig: /var/snap/microk8s/current/credentials/client.config
    state: present
    namespace: wikijs
    src: /tmp/config_wikijs.yml

- name: Create wikijs-pgsql Service
  kubernetes.core.k8s:
    kubeconfig: /var/snap/microk8s/current/credentials/client.config
    state: present
    namespace: wikijs
    src: /tmp/service_wikijs.yml

- name: Create wikijs Deployment
  kubernetes.core.k8s:
    kubeconfig: /var/snap/microk8s/current/credentials/client.config
    state: present
    namespace: wikijs
    src: /tmp/deployment_wikijs.yml

- name: Wait for wikijs pods to come online
  shell: microk8s kubectl get pods -n wikijs -o json
  register: kubectl_get_pod
  until: kubectl_get_pod.stdout|from_json|json_query('items[*].status.phase')|unique == ["Running"]
  retries: 10
  delay: 15

- name: Get wikijs database pod name
  command:
    cmd: microk8s kubectl get pods -n wikijs -l=app=pgsql --no-headers -o custom-columns=":metadata.name"
  register: pod_pgsql

- name: Copy wikijs database backup file to postgres pod
  copy:
    src: /mnt/storage/backup/wikijs/wikibackup.tar
    dest: /mnt/storage/wikijs/postgres/
    remote_src: true

- name: Drop wikijs database
  kubernetes.core.k8s_exec:
    kubeconfig: /var/snap/microk8s/current/credentials/client.config
    namespace: wikijs
    pod: "{{ pod_pgsql.stdout }}"
    container: pgsql
    command: dropdb -U wikijs wikijs -f

- name: Create wikijs database
  kubernetes.core.k8s_exec:
    kubeconfig: /var/snap/microk8s/current/credentials/client.config
    namespace: wikijs
    pod: "{{ pod_pgsql.stdout }}"
    container: pgsql
    command: createdb -U wikijs wikijs

- name: Get wikijs database latest backup
  command:
    cmd: microk8s kubectl exec -it -n wikijs $pod_str -- /bin/bash -c "ls -u /var/lib/postgresql/data/*wikibackup* | head -1"
  register: backup_postgres
  
- name: Restore wikijs database
  kubernetes.core.k8s_exec:
    kubeconfig: /var/snap/microk8s/current/credentials/client.config
    namespace: wikijs
    pod: "{{ pod_pgsql.stdout }}"
    container: pgsql
    command: pg_restore -U wikijs -d wikijs "{{ backup_postgres }}"

- name: Restart wikijs deployment
  command:
    cmd: microk8s kubectl rollout restart -n wikijs deployment/wikijs

- name: Copy wikijs backup script to Host
  become: true
  copy:
    src: /home/vagrant/ansible/playbooks/roles/microk8s_wikijs/files/wikijs_backup.sh
    dest: /usr/sbin/
    owner: root
    group: root
    mode: 0755
    
- name: Create cronjob to backup the wikijs database each night
  ansible.builtin.cron:
    name: "wikijs database backup"
    minute: "0"
    hour: "0"
    job: "/usr/sbin/wikijs_backup.sh"
