---
- name: Create mount points on MicroK8s Node | wikijs
  ansible.builtin.file:
    path: /mnt/storage/wikijs
    state: directory
    mode: '0755'
    owner: nobody
    group: nogroup

- name: Create wikijs namespace
  kubernetes.core.k8s:
    kubeconfig: /var/snap/microk8s/current/credentials/client.config
    name: wikijs-ns
    api_version: v1
    kind: Namespace
    state: present

- name: Copy k8s yaml files to Node
  become: true
  copy:
    src: /home/vagrant/ansible/playbooks/roles/microk8s_wikijs/files
    dest: /tmp/

- name: Apply Secrets
  kubernetes.core.k8s:
    kubeconfig: /var/snap/microk8s/current/credentials/client.config
    state: present
    namespace: wikijs-ns
    src: /tmp/secrets_wikijs.yml

- name: Create Persistent Volume
  kubernetes.core.k8s:
    kubeconfig: /var/snap/microk8s/current/credentials/client.config
    state: present
    namespace: wikijs-ns
    src: /tmp/pv_wikijs.yml

- name: Create Persistent Volume Claim
  kubernetes.core.k8s:
    kubeconfig: /var/snap/microk8s/current/credentials/client.config
    state: present
    namespace: wikijs-ns
    src: /tmp/pvc_wikijs.yml

- name: Create Config Map
  kubernetes.core.k8s:
    kubeconfig: /var/snap/microk8s/current/credentials/client.config
    state: present
    namespace: wikijs-ns
    src: /tmp/config_wikijs.yml

- name: Create wikijs Service
  kubernetes.core.k8s:
    kubeconfig: /var/snap/microk8s/current/credentials/client.config
    state: present
    namespace: wikijs-ns
    src: /tmp/service_wikijs.yml

- name: Create Deployment
  kubernetes.core.k8s:
    kubeconfig: /var/snap/microk8s/current/credentials/client.config
    state: present
    namespace: wikijs-ns
    src: /tmp/deployment_wikijs.yml