---
- name: Ubuntu | Install MicroK8s using snap
  community.general.snap:
    name: microk8s
    classic: true
    channel: '1.27'
    
- name: Ubuntu | Join vagrant user to microk8s group
  user:
     name: vagrant
     groups: microk8s
     append: yes
     
- name: Create kubectl alias for microk8s
  community.general.snap_alias:
    name: microk8s
    alias: kubectl
    
- name: enable dns addon
  command:
    cmd: kubectl enable dns
    
- name: enable hostpath-storage addon
  command:
    cmd: kubectl enable hostpath-storage
    
- name: enable dashboard addon
  command:
    cmd: kubectl enable dashboard

- name: enable ingress addon
  command:
    cmd: kubectl enable ingress
    
- name: enable host-access addon
  command:
    cmd: kubectl enable host-access

- name: Change kubernetes-dashboard service to NodePort
  command:
    cmd: microk8s kubectl patch -n kube-system svc kubernetes-dashboard -p '{"spec": {"type": "NodePort"}}'

- name: Get port that kubernetes-dashboard service is using
  command:
    cmd: microk8s kubectl -n kube-system get services kubernetes-dashboard
  register: kubernetes-dashboard-port
- debug: msg="{{ kubernetes-dashboard-port.stdout }}"
- debug: msg="{{ kubernetes-dashboard-port.stderr }}"
    
