---
- name: install pre-requisites
  pip:
    name:
      - kubernetes
      
- name: Ubuntu | Install MicroK8s using snap
  community.general.snap:
    name: microk8s
    classic: true
    channel: '1.27'
    
- name: Ubuntu | Join vagrant user to microk8s group
  user:
     name: vagrant
     groups: microk8s
     append: yes
     
- name: Create kubectl alias for microk8s
  community.general.snap_alias:
    name: microk8s
    alias: kubectl
    
- name: enable dns addon
  command:
    cmd: kubectl enable dns
    
- name: enable hostpath-storage addon
  command:
    cmd: kubectl enable hostpath-storage
    
- name: enable dashboard addon
  command:
    cmd: kubectl enable dashboard

- name: enable ingress addon
  command:
    cmd: kubectl enable ingress
    
- name: enable host-access addon
  command:
    cmd: kubectl enable host-access
    
- name: Change kubernetes-dashboard service to NodePort
  kubernetes.core.k8s_service:
    kubeconfig: /var/snap/microk8s/5643/credentials/client.config
    state: present
    name: kubernetes-dashboard
    namespace: kube-system
    inline:
      spec:
        externalTrafficPolicy: Cluster
        internalTrafficPolicy: Cluster
        ipFamilies:
        - IPv4
        ipFamilyPolicy: SingleStack
        ports:
        - nodePort: 32075
          port: 443
          protocol: TCP
          targetPort: 8443
        selector:
          k8s-app: kubernetes-dashboard
        sessionAffinity: None
        type: NodePort
