apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-r
  namespace: wordpress-r
  labels:
    app: wordpress-r
spec:
  selector:
    matchLabels:
      app: wordpress-r
  template:
    metadata:
      labels:
        app: wordpress-r
    spec:
      containers:
      - image: wordpress:6.3.2-apache
        imagePullPolicy: Always
        name: wordpress-r
        env:
        - name: WORDPRESS_DB_HOST
          value: mysql-r
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret-r
              key: PASSWORD
        - name: WORDPRESS_DB_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secret-r
              key: USER
        ports:
        - containerPort: 80
          name: wordpress-r
        volumeMounts:
        - name: wordpress-persistent-storage-r
          mountPath: /var/www/html
      volumes:
      - name: wordpress-persistent-storage-r
        persistentVolumeClaim:
          claimName: wordpress-pv-claim-r