apiVersion: v1
kind: Service
metadata:
  name: "wordpress-r"
  namespace: wordpress-r
spec:
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30333
  selector:
    app: "wordpress-r"