apiVersion: v1
kind: Secret
metadata:
  name: database-secret
  namespace: database
type: Opaque
data:
  ROOT: cm9vdA==
  ROOT_PASSWORD: U3Ryb25nUm9vdFBhc3N3b3Jk
  DATABASE: dGVzdA==
  USER: dXNlcg==
  PASSWORD: cGFzc3dvcmQ=
