apiVersion: v1
kind: Service
metadata:
  name: "database"
  namespace: database
spec:
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 3306
      targetPort: 3306
      nodePort: 30334
  selector:
    app: "database"