---
- name: Update and Upgrade
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400

- name: Install Nginx
  apt:
    name: nginx
    state: latest

- name: Ensure nginx is running
  systemd:
    name: nginx
    state: started
    enabled: yes

- name: Create mount web directories | bluegoat
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
    owner: www-data
    group: www-data
  loop:
    - /var/www/html/bluegoat.org
    - /var/www/html/chores.bluegoat.org
    - /var/www/html/cypher.bluegoat.org
    - /var/www/html/matt.bluegoat.org
    - /var/www/html/jon.bluegoat.org
    - /var/www/html/robbie.bluegoat.org
    - /var/www/html/scott.bluegoat.org
    - /var/www/html/trent.bluegoat.org
    - /var/www/html/zaid.bluegoat.org

  - name: Copy index files to webserver
    copy:
      src: {{ item.src }}
      dest: {{ item.sdest }}
      owner: www-data
      group: www-data
      mode: u=rw, g=rw, o=r
    with_items:
      - { src: index.html, dest: /var/www/html/bluegoat.org/index.html }
      - { src: index_chores.html, dest: /var/www/html/chores.bluegoat.org/index.html }
      - { src: index_cypher.html, dest: /var/www/html/cypher.bluegoat.org/index.html }
