---
apiVersion: v1
kind: Service
metadata:
  name: pgsql
  namespace: wikijs-pgsql-ns
spec:
  selector:
    app: pgsql
  ports:
  - name: pgsql
    protocol: TCP
    port: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgsql
  namespace: wikijs-pgsql-ns
  labels:
    app: pgsql
spec:
  selector:
    matchLabels:
      app: pgsql
  template:
    metadata:
      labels:
        app: pgsql
    spec:
      containers:
      - name: pgsql
        image: postgres:latest
        env:
        - name: POSTGRES_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pgsql-secret
              key: ROOT_PASSWORD
        - name: POSTGRES_DATABASE
          valueFrom:
            secretKeyRef:
              name: pgsql-secret
              key: DATABASE
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: pgsql-secret
              key: USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pgsql-secret
              key: PASSWORD
        - name: POSTGRES_ROOT_HOST
          value: "%"
        ports:
        - containerPort: 5432
          name: pgsql
        volumeMounts:
        - name: wikijs-db
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: wikijs-db
        persistentVolumeClaim:
          claimName: wikijs-db-pgsql-pv-claim
