apiVersion: v1
kind: PersistentVolume
metadata:
  name: wikijs-db-pgsql-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/storage/wikijs-pgsql"
