apiVersion: v1
kind: Service
metadata:
  name: "wikijs"
  namespace: wikijs-pgsql-ns
spec:
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30331
  selector:
    app: "wikijs"
