apiVersion: v1
kind: Service
metadata:
  name: "utorrent"
  namespace: utorrent
spec:
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30332
    - name: torrent-tcp
      protocol: TCP
      port: 6881
      targetPort: 6881
    - name: torrent-udp
      protocol: UDP
      port: 6881
      targetPort: 6881
  selector:
    app: "utorrent"