apiVersion: v1
kind: Service
metadata:
  name: homepage-service
spec:
  selector:
    app: nginx
  type: LoadBalancer
  loadBalancerIP: 192.168.1.241
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: 30001