---
- name: Configure the microK8s cluster
  import_playbook: configure_microk8s_cluster.yml
  tags: cluster

- name: Configure DLNA
  import_playbook: configure_dlna_server.yml
  tags: dlna

- name: Configure Samba
  import_playbook: configure_samba.yml
  tags: samba

- name: Configure Wikijs
  import_playbook: configure_wikijs.yml
  tags: wikijs

- name: Configure Homepage
  import_playbook: configure_homepage.yml
  tags: homepage

- name: Configure Wordpress
  import_playbook: configure_wordpress.yml
  tags: wordpress

- name: Configure utorrent
  import_playbook: configure_utorrent.yml
  tags: utorrent

- name: Configure database
  import_playbook: configure_database.yml
  tags: database

- name: Configure cloud vm
  import_playbook: configure_cloud_vm.yml
  tags:
    - cloud_vm
    - never
  when: inventory_hostname in groups["cloud"]
