---
- import_playbook: configure_microk8s_cluster.yml
- import_playbook: configure_dlna_server.yml
- import_playbook: configure_samba.yml
- import_playbook: configure_wikijs.yml
- import_playbook: configure_homepage.yml
- import_playbook: configure_wordpress.yml