---
- name: Create mount points on MicroK8s Node | mysql_r
  ansible.builtin.file:
    path: /mnt/storage/wordpress_r/mysql_r
    state: directory
    mode: '0755'
    owner: nobody
    group: nogroup
  tags: restore

- name: Create mount points on MicroK8s Node | wordpress_r
  ansible.builtin.file:
    path: /mnt/storage/wordpress_r/wordpress_r
    state: directory
    mode: '0777'
    owner: nobody
    group: nogroup
  tags: restore

- name: Create wordpress_r namespace
  kubernetes.core.k8s:
    kubeconfig: /var/snap/microk8s/current/credentials/client.config
    name: wordpress-r
    api_version: v1
    kind: Namespace
    state: present
  tags: restore

- name: Copy k8s yaml files to Node
  become: true
  copy:
    src: /home/vagrant/ansible/playbooks/roles/microk8s_wordpress_r/files/
    dest: /tmp/
  tags: restore

- name: Apply Secrets
  kubernetes.core.k8s:
    kubeconfig: /var/snap/microk8s/current/credentials/client.config
    state: present
    namespace: wordpress-r
    src: /tmp/secrets_mysql_r.yml
  tags: restore

- name: Create Persistent Volume | wordpress_r
  kubernetes.core.k8s:
    kubeconfig: /var/snap/microk8s/current/credentials/client.config
    state: present
    namespace: wordpress-r
    src: /tmp/pv_wordpress_r.yml
  tags: restore

- name: Create Persistent Volume Claim | wordpress_r
  kubernetes.core.k8s:
    kubeconfig: /var/snap/microk8s/current/credentials/client.config
    state: present
    namespace: wordpress-r
    src: /tmp/pvc_wordpress_r.yml
  tags: restore

- name: Create Persistent Volume | wordpress_db_r
  kubernetes.core.k8s:
    kubeconfig: /var/snap/microk8s/current/credentials/client.config
    state: present
    namespace: wordpress-r
    src: /tmp/pv_mysql_r.yml
  tags: restore

- name: Create Persistent Volume Claim | wordpress_db_r
  kubernetes.core.k8s:
    kubeconfig: /var/snap/microk8s/current/credentials/client.config
    state: present
    namespace: wordpress-r
    src: /tmp/pvc_mysql_r.yml
  tags: restore

- name: Create mysql_r Deployment
  kubernetes.core.k8s:
    kubeconfig: /var/snap/microk8s/current/credentials/client.config
    state: present
    namespace: wordpress-r
    src: /tmp/deployment_mysql_r.yml
  tags: restore

- name: Create wordpress-mysql_r Service
  kubernetes.core.k8s:
    kubeconfig: /var/snap/microk8s/current/credentials/client.config
    state: present
    namespace: wordpress-r
    src: /tmp/service_wordpress_r.yml
  tags: restore

- name: Create wordpress_r Deployment
  kubernetes.core.k8s:
    kubeconfig: /var/snap/microk8s/current/credentials/client.config
    state: present
    namespace: wordpress-r
    src: /tmp/deployment_wordpress_r.yml
  tags: restore