apiVersion: v1
kind: PersistentVolume
metadata:
  name: handbrake
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  claimRef:
    kind: PersistentVolumeClaim
    namespace: handbrake
    name: handbrake-pv-claim-watch
  hostPath:
    path: "/mnt/storage/handbrake/watch"