apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: handbrake-pv-claim-watch
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi