apiVersion: v1
kind: Service
metadata:
  name: "handbrake"
  namespace: handbrake
spec:
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 5800
      targetPort: 5800
      nodePort: 30337
  selector:
    app: "handbrake"