apiVersion: v1
kind: Service
metadata:
  name: "chores"
  namespace: chores
spec:
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30332
  selector:
    app: "chores"