apiVersion: v1
kind: Service
metadata:
  name: "chores"
  namespace: chores
spec:
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30336
  selector:
    app: "chores"