---
- name: Create mount points on MicroK8s Node | Movies
  ansible.builtin.file:
    path: /mnt/storage/Movies
    state: directory
    mode: '0755'
    owner: nobody
    group: nogroup

- name: Create mount points on MicroK8s Node | TV
  ansible.builtin.file:
    path: /mnt/storage/TV
    state: directory
    mode: '0755'
    owner: nobody
    group: nogroup

- name: Create dlna namespace
  kubernetes.core.k8s:
    kubeconfig: /var/snap/microk8s/current/credentials/client.config
    name: dlna-ns
    api_version: v1
    kind: Namespace
    state: present

- name: Copy pv_dlna.yml to Node
  become: true
  copy:
    src: /home/vagrant/ansible/k8s/dlna/pv_dlna.yml
    dest: /tmp/pv_dlna.yml

- name: Copy pvc_dlna.yml to Node
  become: true
  copy:
    src: /home/vagrant/ansible/k8s/dlna/pvc_dlna.yml
    dest: /tmp/pvc_dlna.yml

- name: Copy deployment_dlna.yml to Node
  become: true
  copy:
    src: /home/vagrant/ansible/k8s/dlna/deployment_dlna.yml
    dest: /tmp/deployment_dlna.yml

- name: Create Persistent Volume
  kubernetes.core.k8s:
    kubeconfig: /var/snap/microk8s/current/credentials/client.config
    state: present
    namespace: dlna-ns
    src: /tmp/pv_dlna.yml

- name: Create Persistent Volume Claim
  kubernetes.core.k8s:
    kubeconfig: /var/snap/microk8s/current/credentials/client.config
    state: present
    namespace: dlna-ns
    src: /tmp/pvc_dlna.yml

- name: Create Deployment
  kubernetes.core.k8s:
    kubeconfig: /var/snap/microk8s/current/credentials/client.config
    state: present
    namespace: dlna-ns
    src: /tmp/deployment_dlna.yml
