apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wikijs-db-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
