apiVersion: v1
kind: PersistentVolume
metadata:
  name: dlna-pv
  labels:
    type: local
spec:
  claimRef:
    namespace: handbrake
    name: handbrake-persistent-storage
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/storage/minidlna"